<a href="https://colab.research.google.com/github/polilio/notes-for-deep-learning-study/blob/main/pytorch_study_%E6%95%B0%E6%8D%AE%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

张量(tensor)表示由一个数值组成的数组，这个数组可能有多个维度。具有一个轴的张量对应数学上的向量（vector）。具有两个轴的张量对应数学上的矩阵（matrix）。具有两个轴以上的张量没有特殊的数学名称。

In [2]:
x = torch.arange(12) # 创建一个包含12个元素的一维张量: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape # torch.Size([12])
x.dtype # torch.int64
x.numel() # 查看x中元素的总数

12

In [4]:
# 改变张量的形状 （并不会在原对象上修改，而是产生一个新对象）
X = x.reshape(3, 4)
X 
# tensor([[ 0,  1,  2,  3],
#     [ 4,  5,  6,  7],
#     [ 8,  9,  10, 11]])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [5]:
# 常用的创建tensor的方法
torch.zeros((2,3,4))
torch.ones((2,3,4))
torch.randn(2,3,4) # 每个元素都从均值为0、标准差为1的标准高斯（正态）分布中随机采样
torch.tensor([[1,2,4],[4,3,5]]) # 通过python列表构造tensor

tensor([[1, 2, 4],
        [4, 3, 5]])

In [14]:
# 常用运算
x1 = torch.tensor([1,0.2,3,0.8])
x2 = torch.tensor([0.1,0.2,2,0.5])
x1+x2 # tensor([1.1000, 0.4000, 5.0000, 1.3000])
x1-x2 # tensor([0.9000, 0.0000, 1.0000, 0.3000])
x1*x2 # tensor([0.1000, 0.0400, 6.0000, 0.4000])
x1/x2 # tensor([10.0000,  1.0000,  1.5000,  1.6000])
x1**x2 # tensor([1.0000, 0.7248, 9.0000, 0.8944])
torch.exp(x1) # tensor([ 2.7183,  1.2214, 20.0855,  2.2255])

tensor([ 2.7183,  1.2214, 20.0855,  2.2255])

In [17]:
# 连接concatenate
X = torch.arange(12,dtype=torch.float32).reshape(3,-1)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X,Y)) # 默认按照dim=0 concatenate
torch.cat((X,Y),dim=1) # 指定dim=1 concatenate

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [18]:
# bool 张量
bool_tensor = (X == Y)
bool_tensor

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [19]:
# summation of all the elements in the tensor
X.sum() # tensor(66.) a new tensor with exactly one element

tensor(66.)

In [25]:
# broadcast
a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(1,2)
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [27]:
# indexing and slicing
X[-1] # tensor([ 8.,  9., 10., 11.])
X[1:3] # tensor([[ 4.,  5.,  6.,  7.],
    #     [ 8.,  9., 10.,  11.]])


tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [29]:
# 减少内存开销的方式！
# 浪费内存的写法：
before = id(Y)
Y = Y + X
id(Y) == before # False

# 节省内存的写法
before = id(Y)
Y[:] = Y + X
id(Y) == before # True

True

In [34]:
# 转换为其他 Python 对象
A = X.numpy()
B = torch.tensor(A)
print(type(A),",",type(B))

<class 'numpy.ndarray'> , <class 'torch.Tensor'>


In [38]:
# 要将大小为1的张量转换为Python标量
a = torch.tensor([3.5])
int(a) # 3
float(a) # 3.5
a.item() # 3.5

3.5