<a href="https://colab.research.google.com/github/polilio/notes-for-deep-learning-study/blob/main/tensorflow%20version/tensorflow_study%E2%80%94%E2%80%94%E6%95%B0%E6%8D%AE%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
x = tf.range(12) # <tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

In [3]:
x.shape # TensorShape([12])
x.dtype # tf.int32
tf.size(x) # <tf.Tensor: shape=(), dtype=int32, numpy=12> 查看元素总数

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [4]:
# 改变张量的形状 （并不会在原对象上修改，而是产生一个新对象）
X = tf.reshape(x,(3,4))
X

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [5]:
# 常用的创建tensor的方法
tf.zeros((2,3,4))
tf.ones((2,3,4))
tf.random.normal((2,3,4)) # 每个元素都从均值为0、标准差为1的标准高斯（正态）分布中随机采样
tf.constant([[1,2,4],[4,3,5]]) # 通过python列表构造tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 4],
       [4, 3, 5]], dtype=int32)>

In [12]:
# 常用运算
x1 = tf.constant([4,3,5])
x2 = tf.constant([1,2,4])
x1+x2 # <tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 5, 9], dtype=int32)>
x1-x2 # <tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 1, 1], dtype=int32)>
x1*x2 # <tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  6, 20], dtype=int32)>
x1/x2 # <tf.Tensor: shape=(3,), dtype=float64, numpy=array([4.  , 1.5 , 1.25])>
x1**x2 # <tf.Tensor: shape=(3,), dtype=int32, numpy=array([  4,   9, 625], dtype=int32)>
x3 = tf.constant([0.1,0.2,1])
tf.exp(x3) # 这个操作只支持float数

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.105171 , 1.2214028, 2.7182817], dtype=float32)>

In [16]:
# 连接concatenate
X = tf.reshape(tf.range(12,dtype=tf.float32),(3,-1))
Y = tf.constant([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
tf.concat((X,Y),axis=0) # 默认按照dim=0 concatenate
tf.concat((X,Y),axis=1) # 指定dim=1 concatenate

<tf.Tensor: shape=(3, 8), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
       [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
       [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]], dtype=float32)>

In [18]:
# bool 张量
bool_tensor = (X == Y)
bool_tensor

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])>

In [21]:
# summation of all the elements in the tensor
tf.reduce_sum(X) # <tf.Tensor: shape=(), dtype=float32, numpy=66.0>

<tf.Tensor: shape=(), dtype=float32, numpy=66.0>

In [24]:
a = tf.reshape(tf.range(3),(3,1))
b = tf.reshape(tf.range(2),(1,2))
a+b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]], dtype=int32)>

In [26]:
# indexing and slicing
X[-1] # <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>
X[1:3] # <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
    # array([[ 4.,  5.,  6.,  7.],
    #     [ 8.,  9., 10., 11.]], dtype=float32)>


<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [29]:
# tensorflow 不支持切片或者索引直接用=赋值！！！
# TensorFlow中的Tensors是不可变的，也不能被赋值。
# TensorFlow中的Variables是支持赋值的可变容器。请记住，TensorFlow中的梯度不会通过Variable反向传播。
X_var = tf.Variable(X)
X_var[1, 2].assign(9)
X_var
# <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
# array([[ 0.,  1.,  2.,  3.],
#    [ 4.,  5.,  9.,  7.],
#    [ 8.,  9., 10., 11.]], dtype=float32)>

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

由于TensorFlow的Tensors是不可变的，而且梯度不会通过Variable流动，因此TensorFlow没有提供一种明确的方式来原地运行单个操作。

但是，TensorFlow提供了tf.function修饰符，将计算封装在TensorFlow图中，该图在运行前经过编译和优化。这允许TensorFlow删除未使用的值，并复用先前分配的且不再需要的值。这样可以最大限度地减少TensorFlow计算的内存开销。

In [30]:
# 减少内存开销的方式！
# 浪费内存的写法：
before = id(Y)
Y = Y + X
id(Y) == before # False

# 节省内存的写法
@tf.function
def computation(X, Y):
    Z = tf.zeros_like(Y)  # 这个未使用的值将被删除
    A = X + Y  # 当不再需要时，分配将被复用
    B = A + Y
    C = B + Y
    return C + Y

computation(X, Y)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[  8.,  17.,  42.,  51.],
       [ 56.,  73.,  90., 107.],
       [120., 129., 138., 147.]], dtype=float32)>

In [33]:
# 转换为其他 Python 对象
A = X.numpy()
B = tf.constant(A)
print(type(A),",",type(B))

<class 'numpy.ndarray'> , <class 'tensorflow.python.framework.ops.EagerTensor'>


In [35]:
# 要将大小为1的张量转换为Python标量
a = tf.constant([3.5]).numpy()
int(a) # 3
float(a) # 3.5
a.item() # 3.5

3.5